dependencies:
  module:
    - taxonomy_access_fix
  config:
    - user.role.authenticated
items:
  user.role.authenticated:
    expected_config:
      permissions: { }
    update_actions:
      add:
        permissions:
          - 'view terms in nationality'
          - 'view term names in nationality'
          - 'select terms in nationality'
