waap_login.mail:
  type: config_object
  label: 'WaaP Login email settings'
  mapping:
    email_verification:
      type: mapping
      label: 'Email verification'
      mapping:
        subject:
          type: text
          label: 'Subject'
        body:
          type: text
          label: 'Body'
